import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import LanguageProvider from "@/lib/Providers/LanguageProvider";
import { AuthProvider } from "@/lib/Providers/authProvider";
import { CartProvider } from "@/lib/Providers/CartProvider";

// English font
const notoSans = Noto_Sans({
  variable: "--font-english",
  subsets: ["latin"],
});

// Bangla font
const notoBengali = Noto_Sans_Bengali({
  variable: "--font-bengali",
  subsets: ["bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoBengali.variable} antialiased`}
      >
        <LanguageProvider>
          <AuthProvider>
            <CartProvider>{children}</CartProvider>
          </AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
